package com.example.projectmanagement.ui.viewmodel

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.projectmanagement.datageneral.model.Project
import com.example.projectmanagement.datageneral.repository.SupabaseSyncRepository
import com.example.projectmanagement.ui.common.UiState
import kotlinx.coroutines.launch
import java.time.LocalDate

class CreateProjectViewModel(
    private val syncRepository: SupabaseSyncRepository
) : ViewModel() {
    private var editingProjectId: String? = null
    val projectName = MutableLiveData<String>()
    val description = MutableLiveData<String>()
    
    private val _saveState = MutableLiveData<UiState<Project>>()
    val saveState: LiveData<UiState<Project>> = _saveState
    
    private val _projectNameError = MutableLiveData<String?>()
    val projectNameError: LiveData<String?> = _projectNameError

    fun loadProjectDetails(id: String) {
        if (editingProjectId == id) return
        editingProjectId = id

        viewModelScope.launch {
            try {
                // Use the suspend function 'getProject' from your repository
                val project = syncRepository.getProject(id)

                project?.let {
                    // Accessing .title and .description directly
                    projectName.value = it.title
                    description.value = it.description
                }
            } catch (e: Exception) {
                _saveState.postValue(UiState.Error("Failed to load project details"))
            }
        }
    }

    fun saveProject() {
        val nameValue = projectName.value?.trim() ?: ""
        if (nameValue.isEmpty()) return // Add your validation check here

        _saveState.value = UiState.Loading

        viewModelScope.launch {
            try {
                if (editingProjectId == null) {
                    // CREATE MODE: Calls insertProjectAndSync
                    val newProject = Project(
                        id = "", // Repo will generate UUID
                        title = nameValue,
                        description = description.value ?: "",
                        inviteCode = null,
                        createdAt = null
                    )
                    val result = syncRepository.insertProjectAndSync(newProject)
                    _saveState.postValue(UiState.Success(result))
                } else {
                    // EDIT MODE: Calls updateProject
                    val updatedProject = Project(
                        id = editingProjectId!!,
                        title = nameValue,
                        description = description.value ?: "",
                        inviteCode = null,
                        createdAt = null
                    )
                    syncRepository.updateProject(updatedProject)
                    _saveState.postValue(UiState.Success(updatedProject))
                }
            } catch (e: Exception) {
                _saveState.postValue(UiState.Error(e.message ?: "Unknown error"))
            }
        }
    }
    
    fun clearErrors() {
        _projectNameError.value = null
    }
    
    fun setProjectName(name: String) {
        projectName.value = name
    }
    
    fun setDescription(desc: String) {
        description.value = desc
    }
    
    private fun isEntryValid(nameValue: String): Boolean {
        return if (nameValue.isEmpty()) {
            _projectNameError.value = "Project name is required"
            false
        } else {
            _projectNameError.value = null
            true
        }
    }
    
    private fun getNewProjectEntry(nameValue: String): Project {
        // Set creation date to current system date in ISO format
        val currentDate = java.time.LocalDate.now().toString()
        // Generate UUID for the project
        val projectId = java.util.UUID.randomUUID().toString()
        return Project(
            id = projectId,
            title = nameValue,
            description = description.value ?: "",
            inviteCode = null, // Will be generated by Supabase
            createdAt = currentDate
        )
    }
}

class CreateProjectViewModelFactory(private val syncRepository: SupabaseSyncRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(CreateProjectViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return CreateProjectViewModel(syncRepository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}

